//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assay
    {
        public Assay()
        {
            this.MeasureCards = new HashSet<MeasureCard>();
        }
    
        public long AssayID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<long> ProductUnitID { get; set; }
        public Nullable<long> Color { get; set; }
        public Nullable<long> ContractID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public string Notes { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<MeasureCard> MeasureCards { get; set; }
    }
}
