//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_CityPray
    {
        public long ID { get; set; }
        public string IdCode { get; set; }
        public Nullable<long> CountryId { get; set; }
        public string NameE { get; set; }
        public string Name { get; set; }
        public string Long { get; set; }
        public string Lat { get; set; }
        public string Zone { get; set; }
        public bool Hide { get; set; }
    }
}
