//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_Permission
    {
        public att_Permission()
        {
            this.att_EmpPermission = new HashSet<att_EmpPermission>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<att_EmpPermission> att_EmpPermission { get; set; }
    }
}
