//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_Holiday
    {
        public att_Holiday()
        {
            this.att_EmpHolidayRecord = new HashSet<att_EmpHolidayRecord>();
            this.att_PublicHolidayRecord = new HashSet<att_PublicHolidayRecord>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> Relgion { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> type { get; set; }
        public bool isContinous { get; set; }
    
        public virtual att_DayState att_DayState { get; set; }
        public virtual ICollection<att_EmpHolidayRecord> att_EmpHolidayRecord { get; set; }
        public virtual Relgion Relgion1 { get; set; }
        public virtual ICollection<att_PublicHolidayRecord> att_PublicHolidayRecord { get; set; }
    }
}
