//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_PrayRule
    {
        public long ID { get; set; }
        public Nullable<long> id_pray { get; set; }
        public Nullable<long> beforPray { get; set; }
        public Nullable<long> afterPray { get; set; }
        public string Notes { get; set; }
        public long Name { get; set; }
    }
}
