//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_ShiftsTimes
    {
        public long ID { get; set; }
        public long ShiftID { get; set; }
        public long WorkTimeID { get; set; }
        public short DayID { get; set; }
    
        public virtual att_Shifts att_Shifts { get; set; }
        public virtual att_WeekDays att_WeekDays { get; set; }
        public virtual att_workTimeRecord att_workTimeRecord { get; set; }
    }
}
