//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_UsersLogs
    {
        public long ID { get; set; }
        public int DeviceUserID { get; set; }
        public int VerifyMode { get; set; }
        public int InOutMode { get; set; }
        public System.DateTime Time { get; set; }
        public string WorkCode { get; set; }
        public short Type { get; set; }
    }
}
