//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_DayState
    {
        public att_DayState()
        {
            this.att_attendance = new HashSet<att_attendance>();
            this.att_Holiday = new HashSet<att_Holiday>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<att_attendance> att_attendance { get; set; }
        public virtual ICollection<att_Holiday> att_Holiday { get; set; }
    }
}
