//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_prevEmpHoliday
    {
        public long ID { get; set; }
        public Nullable<long> EmpID { get; set; }
        public int prevNumberHoliday { get; set; }
        public int prevBlancedHoliday { get; set; }
    
        public virtual EmployedInfo EmployedInfo { get; set; }
    }
}
