//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_PublicHolidayRecord
    {
        public long ID { get; set; }
        public Nullable<long> PublicHoliday { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> dateTo { get; set; }
        public Nullable<int> year { get; set; }
    
        public virtual att_Holiday att_Holiday { get; set; }
    }
}
