//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_DelayandAbsenceSetting
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string IdCode { get; set; }
        public Nullable<int> TimeDelayStart { get; set; }
        public Nullable<int> TimeDelayend { get; set; }
        public bool ISvalue { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<int> numberDay { get; set; }
        public Nullable<int> salaryItem { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
