//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentSystemFile
    {
        public long IdCode { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public Nullable<long> DocumentOwen { get; set; }
        public string FileName { get; set; }
        public string FileFullPath { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    }
}
