//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceTime
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> daydate { get; set; }
        public Nullable<System.DateTime> attendancetime1 { get; set; }
        public Nullable<System.DateTime> leavingtime { get; set; }
        public Nullable<System.DateTime> breakstart { get; set; }
        public Nullable<System.DateTime> breakend { get; set; }
        public Nullable<int> breaktime { get; set; }
        public Nullable<System.DateTime> breakback { get; set; }
        public Nullable<System.DateTime> maghrib { get; set; }
        public Nullable<int> maghribtime { get; set; }
        public Nullable<System.DateTime> maghribback { get; set; }
        public Nullable<bool> maghribcheck { get; set; }
        public Nullable<System.DateTime> aisha { get; set; }
        public Nullable<int> aishatime { get; set; }
        public Nullable<System.DateTime> aishaback { get; set; }
        public Nullable<bool> aishacheck { get; set; }
        public Nullable<bool> BreakCheckInOut { get; set; }
    }
}
