//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceRule
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> AttendanceTime { get; set; }
        public Nullable<System.DateTime> LeavingTime { get; set; }
        public Nullable<int> BreakFrom { get; set; }
        public Nullable<int> BreakTo { get; set; }
        public Nullable<int> BreakAdditionTime { get; set; }
        public Nullable<int> MaghribBreakTime { get; set; }
        public Nullable<bool> MaghribCheckInOut { get; set; }
        public Nullable<int> AishaBreakTime { get; set; }
        public Nullable<bool> AishaCheckInOut { get; set; }
        public Nullable<bool> BreakCheckInOut { get; set; }
    }
}
