//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceCheckInOut
    {
        public long ID { get; set; }
        public Nullable<long> EmpID { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public string AccessMode { get; set; }
        public Nullable<short> CheckInType { get; set; }
        public Nullable<System.DateTime> LastInserted { get; set; }
    }
}
