//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AzanRule
    {
        public long Id { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longtude { get; set; }
        public Nullable<long> FileID { get; set; }
        public string FilePath { get; set; }
        public Nullable<long> CalcID { get; set; }
        public Nullable<long> JuristicID { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<bool> isPlay { get; set; }
    }
}
