//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankHistoryPlaning
    {
        public long Id { get; set; }
        public Nullable<long> IdBankHistory { get; set; }
        public string CheckNum { get; set; }
        public Nullable<decimal> CheckValue { get; set; }
        public string VoucherType { get; set; }
        public string PayeName { get; set; }
        public Nullable<System.DateTime> Editdate { get; set; }
        public Nullable<System.DateTime> PayableDate { get; set; }
        public string StatePay { get; set; }
        public Nullable<bool> IsAchieve { get; set; }
        public Nullable<bool> IsEndorsement { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    }
}
