//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankInfo
    {
        public BankInfo()
        {
            this.ChequesInfoes = new HashSet<ChequesInfo>();
        }
    
        public long Idcode { get; set; }
        public string Name { get; set; }
        public string AcountType { get; set; }
        public string AcountCrunceyType { get; set; }
        public string AcountNum { get; set; }
        public string Tel { get; set; }
        public string AcountOwner { get; set; }
        public Nullable<decimal> FirstAccount { get; set; }
        public string Branch { get; set; }
        public string BranchAdress { get; set; }
        public Nullable<bool> IsDefult { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DateOpen { get; set; }
        public string Notice { get; set; }
        public byte[] Logo { get; set; }
        public byte[] CheckImage { get; set; }
        public byte[] SigntureImage { get; set; }
        public Nullable<long> PeriodID { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    
        public virtual ICollection<ChequesInfo> ChequesInfoes { get; set; }
    }
}
