//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSC_TimeRecord
    {
        public int UserId { get; set; }
        public int ActionType { get; set; }
        public string Form { get; set; }
        public string Action_Code { get; set; }
        public string Action_TCode { get; set; }
        public System.DateTime DayDate { get; set; }
        public int Serial { get; set; }
    }
}
