//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSC_TimeRecordData
    {
        public System.DateTime DayDate { get; set; }
        public string ActionNo { get; set; }
        public int EventType { get; set; }
        public string Form { get; set; }
        public string Title { get; set; }
        public string Val { get; set; }
        public int Serial { get; set; }
    }
}
