//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSC_Company
    {
        public int Code { get; set; }
        public string Name { get; set; }
        public string EName { get; set; }
        public byte[] Logo { get; set; }
        public string Type { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public byte[] PageLogo { get; set; }
        public string AccSales { get; set; }
        public string AccPurchase { get; set; }
        public string AccResales { get; set; }
        public string AccRePurchase { get; set; }
        public string AccPeriodStart { get; set; }
        public string AccPeriodEnd { get; set; }
        public string AccDiscount { get; set; }
        public string AccDiscountEarned { get; set; }
        public string AccTaxSales { get; set; }
        public string AccTaxAD { get; set; }
        public string AccEznAdd { get; set; }
        public string AccEznSarf { get; set; }
        public string AccIncome { get; set; }
        public Nullable<int> asdint { get; set; }
    }
}
