//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashairUser
    {
        public int ID { get; set; }
        public string UserNameA { get; set; }
        public string UserNameE { get; set; }
        public string Password { get; set; }
        public bool Suspended { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> DefaultWarehouse { get; set; }
        public Nullable<double> DiscountLimit { get; set; }
        public Nullable<bool> IsOwner { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    }
}
