//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequesInfo
    {
        public long Idcode { get; set; }
        public string ChequeNum { get; set; }
        public Nullable<long> BankId { get; set; }
        public string BalanceNum { get; set; }
        public Nullable<System.DateTime> IsdarDate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<long> EmpId { get; set; }
        public Nullable<long> CollectionBankid { get; set; }
        public Nullable<long> PeriodID { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    
        public virtual BankInfo BankInfo { get; set; }
    }
}
