//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Color
    {
        public Color()
        {
            this.Product_Color_Realation = new HashSet<Product_Color_Realation>();
        }
    
        public long Id_Color { get; set; }
        public string Color_Name { get; set; }
        public string Description { get; set; }
        public byte[] ColorImage { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    
        public virtual ICollection<Product_Color_Realation> Product_Color_Realation { get; set; }
    }
}
