//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Companies_Sup = new HashSet<Companies_Sup>();
            this.ItemControls = new HashSet<ItemControl>();
        }
    
        public long ID { get; set; }
        public string CompanyName { get; set; }
        public string Name { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual ICollection<Companies_Sup> Companies_Sup { get; set; }
        public virtual ICollection<ItemControl> ItemControls { get; set; }
    }
}
