//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public long Id { get; set; }
        public string CompanyNameEng { get; set; }
        public string CompanyNameArb { get; set; }
        public string CompanyDescrption { get; set; }
        public string GeneralManegar { get; set; }
        public string NationNum { get; set; }
        public string LinePhone { get; set; }
        public string CellPhone { get; set; }
        public string Fax { get; set; }
        public string UrlSite { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
        public Nullable<long> Country { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> EstablishDate { get; set; }
        public string tradeNum { get; set; }
        public string TaxNum { get; set; }
        public string InsuranceNum { get; set; }
        public byte[] Logo { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    }
}
