//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public Contract()
        {
            this.Assays = new HashSet<Assay>();
            this.ContractItemDescriptions = new HashSet<ContractItemDescription>();
            this.Installments = new HashSet<Installment>();
            this.Payment_Permission = new HashSet<Payment_Permission>();
        }
    
        public long ContractID { get; set; }
        public Nullable<System.DateTime> contractDate { get; set; }
        public Nullable<System.DateTime> ImplementationStartDate { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> EmpID { get; set; }
        public Nullable<long> PeriodID { get; set; }
        public Nullable<long> HRDDepartmentID { get; set; }
        public string PhoneNum { get; set; }
        public string Address { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public string Notes { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public byte[] attachment { get; set; }
    
        public virtual ICollection<Assay> Assays { get; set; }
        public virtual ICollection<ContractItemDescription> ContractItemDescriptions { get; set; }
        public virtual CustomerInfo CustomerInfo { get; set; }
        public virtual HRDepartment HRDepartment { get; set; }
        public virtual ICollection<Installment> Installments { get; set; }
        public virtual ICollection<Payment_Permission> Payment_Permission { get; set; }
    }
}
