//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractItem
    {
        public ContractItem()
        {
            this.HRDeptContractItemRelations = new HashSet<HRDeptContractItemRelation>();
        }
    
        public long ContractItemID { get; set; }
        public string ContractItemDescription { get; set; }
        public Nullable<bool> ApplyToAll { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<HRDeptContractItemRelation> HRDeptContractItemRelations { get; set; }
    }
}
