//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenter
    {
        public long CenterID { get; set; }
        public Nullable<long> HRDepartmentID { get; set; }
        public string HRDepartmentName { get; set; }
        public Nullable<byte> Active { get; set; }
    }
}
