//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryData
    {
        public long Id { get; set; }
        public Nullable<long> IdParant { get; set; }
        public string Display { get; set; }
        public string En_Display { get; set; }
        public string Type { get; set; }
        public string MainCurrancey { get; set; }
        public string SubCurrancey { get; set; }
        public string SamplCurrancey { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    }
}
