//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfo
    {
        public CustomerInfo()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public long IdCode { get; set; }
        public Nullable<long> GroupId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CompanyName { get; set; }
        public string NationNum { get; set; }
        public Nullable<long> Nationalty { get; set; }
        public Nullable<int> IsFogin { get; set; }
        public Nullable<System.DateTime> FirstDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public string Tel { get; set; }
        public string homeTel { get; set; }
        public string CellPhone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<long> Country { get; set; }
        public Nullable<long> State { get; set; }
        public Nullable<long> Tawon { get; set; }
        public string Adress { get; set; }
        public string PstelCode { get; set; }
        public Nullable<decimal> FirsAcount { get; set; }
        public Nullable<decimal> MaxAcount { get; set; }
        public Nullable<decimal> CurrantAcount { get; set; }
        public string Notice { get; set; }
        public string Category { get; set; }
        public string Priorty { get; set; }
        public byte[] CompanyLogo { get; set; }
        public string ComercialNum { get; set; }
        public string TaxNum { get; set; }
        public Nullable<bool> IsBadList { get; set; }
        public Nullable<bool> IsInCourt { get; set; }
        public string C_no { get; set; }
        public Nullable<long> C_n { get; set; }
        public Nullable<long> C_d { get; set; }
        public string LUU { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
    }
}
