//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerGuarantor
    {
        public long IdCode { get; set; }
        public Nullable<long> Cust_IdCode { get; set; }
        public string GuarantorName { get; set; }
        public string GuarantorNationNum { get; set; }
        public string GuarantorPhone { get; set; }
        public string GuarantorAdress { get; set; }
        public Nullable<bool> IsInCourt { get; set; }
        public Nullable<bool> IsInBlackList { get; set; }
    }
}
