//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTLPeriodicalInventory
    {
        public long Id { get; set; }
        public Nullable<long> HDID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<long> UnitId { get; set; }
        public Nullable<double> CurrentQTY { get; set; }
        public Nullable<double> SystemQTY { get; set; }
        public string Notes { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    
        public virtual HDPeriodicalInventory HDPeriodicalInventory { get; set; }
        public virtual ItemControl ItemControl { get; set; }
    }
}
