//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTLPurchaseReturn
    {
        public long Id { get; set; }
        public Nullable<long> HDId { get; set; }
        public Nullable<long> ItemId { get; set; }
        public Nullable<long> UnitId { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> TPriceBeforeDiscount { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public Nullable<double> DiscountPercentage { get; set; }
        public Nullable<decimal> TPriceAfterDiscount { get; set; }
        public Nullable<decimal> TotalCostPrice { get; set; }
        public int ReasonId { get; set; }
        public Nullable<long> HDPurchaseBillId { get; set; }
        public string Notes { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<long> storeId { get; set; }
        public Nullable<double> ReturnQuantity { get; set; }
        public Nullable<decimal> priceCost { get; set; }
        public Nullable<decimal> PriceCostDiscount { get; set; }
        public Nullable<decimal> DiscountValueTotal { get; set; }
        public Nullable<double> DiscountPercentageTotal { get; set; }
    
        public virtual HDPurchaseBill HDPurchaseBill { get; set; }
        public virtual HDPurchaseReturn HDPurchaseReturn { get; set; }
        public virtual ItemControl ItemControl { get; set; }
        public virtual ModelUnit ModelUnit { get; set; }
    }
}
