//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTLStoreReturn
    {
        public long Id { get; set; }
        public Nullable<long> HDId { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<long> UnitId { get; set; }
        public Nullable<double> QtyRwturn { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public string Notes { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    
        public virtual HDStoreReturn HDStoreReturn { get; set; }
        public virtual ItemAmount ItemAmount { get; set; }
        public virtual ItemControl ItemControl { get; set; }
        public virtual MaterialsPayoffReason MaterialsPayoffReason { get; set; }
        public virtual ModelUnit ModelUnit { get; set; }
    }
}
