//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTLSale
    {
        public long ID { get; set; }
        public Nullable<long> HDId { get; set; }
        public Nullable<long> ItemId { get; set; }
        public Nullable<long> ItemBarcode { get; set; }
        public Nullable<long> UnitID { get; set; }
        public double Qty { get; set; }
        public double SalePrice { get; set; }
        public double CostPrice { get; set; }
        public Nullable<double> FreeQty { get; set; }
        public Nullable<double> Discount { get; set; }
        public long counter { get; set; }
    }
}
