//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmplLanguge
    {
        public long id { get; set; }
        public Nullable<long> EmplIdCode { get; set; }
        public Nullable<long> LangugeName { get; set; }
        public string Reading { get; set; }
        public string listener { get; set; }
        public string Write { get; set; }
        public string Speaking { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    
        public virtual EmployedInfo EmployedInfo { get; set; }
        public virtual Language Language { get; set; }
    }
}
