//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmplPayRoll
    {
        public long Id { get; set; }
        public Nullable<long> EmplIdCode { get; set; }
        public string ForMonth { get; set; }
        public Nullable<decimal> BasicSallary { get; set; }
        public Nullable<decimal> PrecentChangeableSallary { get; set; }
        public Nullable<decimal> ChangeableSallary { get; set; }
        public Nullable<decimal> SubstituteResidence { get; set; }
        public Nullable<decimal> SubstituteHighCostOfLiving { get; set; }
        public Nullable<decimal> SubstituteLocomotion { get; set; }
        public Nullable<decimal> SubstituteHealthCare { get; set; }
        public Nullable<decimal> SocialInsurance { get; set; }
        public Nullable<decimal> MedicalInsurance { get; set; }
        public Nullable<decimal> CellPhoneBill { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    }
}
