//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmplScholastic
    {
        public long id { get; set; }
        public Nullable<long> EmplIdCode { get; set; }
        public Nullable<decimal> Grad { get; set; }
        public string CollageName { get; set; }
        public string SchoolName { get; set; }
        public Nullable<long> LeavlGrad { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    
        public virtual EmployedInfo EmployedInfo { get; set; }
    }
}
