//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalaryItem
    {
        public long Id { get; set; }
        public Nullable<long> EmplIdCode { get; set; }
        public Nullable<long> SalaryItemID { get; set; }
        public Nullable<decimal> ItemValue { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    
        public virtual EmployedInfo EmployedInfo { get; set; }
        public virtual SalaryItem SalaryItem { get; set; }
    }
}
