//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployedInfo
    {
        public EmployedInfo()
        {
            this.att_attendance = new HashSet<att_attendance>();
            this.att_EmpHolidayRecord = new HashSet<att_EmpHolidayRecord>();
            this.att_EmpPermission = new HashSet<att_EmpPermission>();
            this.att_prevEmpHoliday = new HashSet<att_prevEmpHoliday>();
            this.AttDevicesUsers = new HashSet<AttDevicesUser>();
            this.EmplCours = new HashSet<EmplCour>();
            this.EmplLanguges = new HashSet<EmplLanguge>();
            this.EmployeDepartments = new HashSet<EmployeDepartment>();
            this.EmployeeSalaryItems = new HashSet<EmployeeSalaryItem>();
            this.EmployeesShifts = new HashSet<EmployeesShift>();
            this.EmplScholastics = new HashSet<EmplScholastic>();
            this.EmplWorkExperinces = new HashSet<EmplWorkExperince>();
            this.HDMaterialsrequests = new HashSet<HDMaterialsrequest>();
            this.HDPurchaseChecks = new HashSet<HDPurchaseCheck>();
            this.HDPurchaseReturns = new HashSet<HDPurchaseReturn>();
            this.HDReceiptOfMaterialsRequests = new HashSet<HDReceiptOfMaterialsRequest>();
            this.HDTransferMaterials = new HashSet<HDTransferMaterial>();
            this.UserNames = new HashSet<UserName>();
        }
    
        public long IdCode { get; set; }
        public string Name { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<long> CarID { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<long> Nationalty { get; set; }
        public Nullable<long> MilitaryState { get; set; }
        public Nullable<long> MaritalState { get; set; }
        public Nullable<long> Relgion { get; set; }
        public Nullable<long> Gender { get; set; }
        public Nullable<long> EmploymentStatusID { get; set; }
        public string licenseCarNum { get; set; }
        public string licenseGun { get; set; }
        public string passportNum { get; set; }
        public string NationalNum { get; set; }
        public string SectionName { get; set; }
        public string Branch { get; set; }
        public Nullable<int> ContractWorkType { get; set; }
        public string SectorName { get; set; }
        public string LevelOccupation { get; set; }
        public string Occupation { get; set; }
        public Nullable<long> ContractPeriod { get; set; }
        public Nullable<long> QuetReason { get; set; }
        public string CountRenewContract { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string OtherQuetReason { get; set; }
        public Nullable<System.DateTime> QuietDate { get; set; }
        public string ProjectGraduate { get; set; }
        public string UrlSite { get; set; }
        public string Email { get; set; }
        public byte[] SignatureImage { get; set; }
        public string SystemEmail { get; set; }
        public string CellPhone { get; set; }
        public string PhoneWork { get; set; }
        public string PhoneHome { get; set; }
        public string Fax { get; set; }
        public string PostelCode { get; set; }
        public string SenderAdress { get; set; }
        public string Streat { get; set; }
        public Nullable<long> State { get; set; }
        public Nullable<long> Towan { get; set; }
        public Nullable<long> HRJobID { get; set; }
        public Nullable<System.DateTime> licenseCarNumStart { get; set; }
        public Nullable<System.DateTime> licenseCarNumEnd { get; set; }
        public Nullable<System.DateTime> licenseGunStart { get; set; }
        public Nullable<System.DateTime> licenseGunEnd { get; set; }
        public Nullable<System.DateTime> passportNumStart { get; set; }
        public Nullable<System.DateTime> passportNumEnd { get; set; }
        public Nullable<System.DateTime> NationalNumStart { get; set; }
        public Nullable<System.DateTime> NationalNumEnd { get; set; }
        public Nullable<long> Country { get; set; }
        public Nullable<double> PercentMony { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<long> AccountID { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<byte> Frequency { get; set; }
        public Nullable<byte> Children { get; set; }
        public long ID { get; set; }
        public string Path { get; set; }
        public byte[] EmplImage { get; set; }
        public bool NotActive { get; set; }
        public Nullable<int> SponsorID { get; set; }
    
        public virtual ICollection<att_attendance> att_attendance { get; set; }
        public virtual ICollection<att_EmpHolidayRecord> att_EmpHolidayRecord { get; set; }
        public virtual ICollection<att_EmpPermission> att_EmpPermission { get; set; }
        public virtual att_EmpSettings att_EmpSettings { get; set; }
        public virtual ICollection<att_prevEmpHoliday> att_prevEmpHoliday { get; set; }
        public virtual ICollection<AttDevicesUser> AttDevicesUsers { get; set; }
        public virtual ICollection<EmplCour> EmplCours { get; set; }
        public virtual ICollection<EmplLanguge> EmplLanguges { get; set; }
        public virtual ICollection<EmployeDepartment> EmployeDepartments { get; set; }
        public virtual EmpSponsor EmpSponsor { get; set; }
        public virtual ICollection<EmployeeSalaryItem> EmployeeSalaryItems { get; set; }
        public virtual ICollection<EmployeesShift> EmployeesShifts { get; set; }
        public virtual ICollection<EmplScholastic> EmplScholastics { get; set; }
        public virtual ICollection<EmplWorkExperince> EmplWorkExperinces { get; set; }
        public virtual ICollection<HDMaterialsrequest> HDMaterialsrequests { get; set; }
        public virtual ICollection<HDPurchaseCheck> HDPurchaseChecks { get; set; }
        public virtual ICollection<HDPurchaseReturn> HDPurchaseReturns { get; set; }
        public virtual ICollection<HDReceiptOfMaterialsRequest> HDReceiptOfMaterialsRequests { get; set; }
        public virtual ICollection<HDTransferMaterial> HDTransferMaterials { get; set; }
        public virtual ICollection<UserName> UserNames { get; set; }
    }
}
