//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenditureHistory
    {
        public long Id { get; set; }
        public string ExpenditureType { get; set; }
        public string BranchType { get; set; }
        public Nullable<decimal> MoneyValue { get; set; }
        public string PayWay { get; set; }
        public string Reason { get; set; }
        public string Notic { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    }
}
