//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeDegree
    {
        public GradeDegree()
        {
            this.EmplCours = new HashSet<EmplCour>();
        }
    
        public long ID { get; set; }
        public string GradeNameAR { get; set; }
        public string GradeNameEN { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<EmplCour> EmplCours { get; set; }
    }
}
