//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDPurchaseOrder
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<long> PeriodId { get; set; }
        public string Notes { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public long Name { get; set; }
        public Nullable<long> idcode { get; set; }
        public Nullable<long> supplierId { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> auto { get; set; }
        public Nullable<long> used { get; set; }
        public string Barcode { get; set; }
        public Nullable<bool> active { get; set; }
        public bool isUsedItemNotActive { get; set; }
    }
}
