//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDPurchaseCheck
    {
        public HDPurchaseCheck()
        {
            this.DTLPurchaseChecks = new HashSet<DTLPurchaseCheck>();
            this.DTLPurchaseCheckTests = new HashSet<DTLPurchaseCheckTest>();
        }
    
        public long Id { get; set; }
        public Nullable<long> HDPurchaseBillId { get; set; }
        public Nullable<long> EmpId { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<long> PeriodId { get; set; }
        public string Notes { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<long> idCode { get; set; }
        public Nullable<long> supplierId { get; set; }
        public Nullable<long> storeId { get; set; }
    
        public virtual ICollection<DTLPurchaseCheck> DTLPurchaseChecks { get; set; }
        public virtual ICollection<DTLPurchaseCheckTest> DTLPurchaseCheckTests { get; set; }
        public virtual EmployedInfo EmployedInfo { get; set; }
        public virtual HDPurchaseBill HDPurchaseBill { get; set; }
    }
}
