//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDPurchaseReturn
    {
        public HDPurchaseReturn()
        {
            this.DTLPurchaseReturns = new HashSet<DTLPurchaseReturn>();
        }
    
        public long Id { get; set; }
        public string IdCode { get; set; }
        public Nullable<long> SuppId { get; set; }
        public Nullable<long> EmpId { get; set; }
        public Nullable<bool> IsReturn { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> ReturnsMoneyAction { get; set; }
        public Nullable<long> SafeId { get; set; }
        public string Notes { get; set; }
        public Nullable<long> PeriodId { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DiscountVal { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<decimal> Expenses { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public string Barcode { get; set; }
    
        public virtual ICollection<DTLPurchaseReturn> DTLPurchaseReturns { get; set; }
        public virtual EmployedInfo EmployedInfo { get; set; }
        public virtual SupplierInfo SupplierInfo { get; set; }
    }
}
