//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDReceiptOfMaterialsRequest
    {
        public HDReceiptOfMaterialsRequest()
        {
            this.DTLReceiptOfMaterialsRequests = new HashSet<DTLReceiptOfMaterialsRequest>();
            this.HDStoreReturns = new HashSet<HDStoreReturn>();
        }
    
        public long Id { get; set; }
        public Nullable<System.DateTime> DateReceiptOfMaterialsRequest { get; set; }
        public Nullable<long> MaterialsRequestID { get; set; }
        public Nullable<long> EmpID { get; set; }
        public Nullable<long> StoreID { get; set; }
        public Nullable<long> ReceiptEmpID { get; set; }
        public string Notes { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<long> PeriodId { get; set; }
    
        public virtual ICollection<DTLReceiptOfMaterialsRequest> DTLReceiptOfMaterialsRequests { get; set; }
        public virtual EmployedInfo EmployedInfo { get; set; }
        public virtual HDMaterialsrequest HDMaterialsrequest { get; set; }
        public virtual StoresCompany StoresCompany { get; set; }
        public virtual ICollection<HDStoreReturn> HDStoreReturns { get; set; }
    }
}
