//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDSale
    {
        public long ID { get; set; }
        public Nullable<int> IDCode { get; set; }
        public Nullable<long> CustID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<double> NetTotal { get; set; }
        public Nullable<double> TotalPaid { get; set; }
        public string ComputerName { get; set; }
        public string Notes { get; set; }
        public Nullable<int> WarehouseID { get; set; }
    }
}
