//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDSalesReturn
    {
        public int VoucherID { get; set; }
        public System.DateTime Date { get; set; }
        public int UserID { get; set; }
        public Nullable<int> SaleBillNo { get; set; }
        public int CustomerID { get; set; }
        public double Total { get; set; }
        public double Discount { get; set; }
        public double NetTotal { get; set; }
        public string Notes { get; set; }
        public Nullable<int> WarehouseID { get; set; }
    }
}
