//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDStoreReturn
    {
        public HDStoreReturn()
        {
            this.DTLStoreReturns = new HashSet<DTLStoreReturn>();
        }
    
        public long Id { get; set; }
        public Nullable<System.DateTime> DateHDStoreReturns { get; set; }
        public Nullable<long> HDReceiptOfMaterialsRequestID { get; set; }
        public Nullable<long> StoreEmpID { get; set; }
        public Nullable<long> RecieveEmpID { get; set; }
        public Nullable<long> StoreID { get; set; }
        public string Notes { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<long> PeriodId { get; set; }
    
        public virtual ICollection<DTLStoreReturn> DTLStoreReturns { get; set; }
        public virtual HDReceiptOfMaterialsRequest HDReceiptOfMaterialsRequest { get; set; }
        public virtual StoresCompany StoresCompany { get; set; }
    }
}
