//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDTransferRequest
    {
        public HDTransferRequest()
        {
            this.DTLTransferRequests = new HashSet<DTLTransferRequest>();
            this.DTLTransferRequestTests = new HashSet<DTLTransferRequestTest>();
        }
    
        public long Id { get; set; }
        public Nullable<System.DateTime> DateRequest { get; set; }
        public Nullable<long> RequestStoreId { get; set; }
        public Nullable<long> RecieveStoreId { get; set; }
        public Nullable<long> RequestEmpId { get; set; }
        public Nullable<long> RecieveEmpId { get; set; }
        public Nullable<long> PeriodId { get; set; }
        public string Notes { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<long> idCode { get; set; }
        public Nullable<long> used { get; set; }
        public string Barcode { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual ICollection<DTLTransferRequest> DTLTransferRequests { get; set; }
        public virtual ICollection<DTLTransferRequestTest> DTLTransferRequestTests { get; set; }
        public virtual StoresCompany StoresCompany { get; set; }
    }
}
