//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRDepartment
    {
        public HRDepartment()
        {
            this.Contracts = new HashSet<Contract>();
            this.EmployeDepartments = new HashSet<EmployeDepartment>();
            this.HRDeptContractItemRelations = new HashSet<HRDeptContractItemRelation>();
        }
    
        public long HRDepartmentID { get; set; }
        public string HRDepartmentName { get; set; }
        public Nullable<long> IdParant { get; set; }
        public string Path { get; set; }
        public Nullable<int> PathLevel { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public long ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<EmployeDepartment> EmployeDepartments { get; set; }
        public virtual ICollection<HRDeptContractItemRelation> HRDeptContractItemRelations { get; set; }
    }
}
