//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoCompany
    {
        public long Id { get; set; }
        public string Idcode { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAdress { get; set; }
        public string Email { get; set; }
        public string ManegrName { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string RegistrCommerce { get; set; }
        public string RegistrTax { get; set; }
        public string InsuranceNum { get; set; }
        public byte[] Image { get; set; }
    }
}
