//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryData
    {
        public long Id { get; set; }
        public Nullable<long> StoreId { get; set; }
        public Nullable<long> IdBill { get; set; }
        public Nullable<int> IdBillType { get; set; }
        public Nullable<long> IdBillSalesReturns { get; set; }
        public Nullable<long> ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<double> UnitsInAmount { get; set; }
        public Nullable<double> CountAmount { get; set; }
        public Nullable<double> StockOnHand { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<decimal> PriceUnit { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string OperationType { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<long> PeriodId { get; set; }
        public Nullable<long> IdBillPurchase { get; set; }
    
        public virtual ItemAmount ItemAmount { get; set; }
        public virtual ItemControl ItemControl { get; set; }
    }
}
