//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryMainFirstPeriod
    {
        public long PeriodId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<long> StoreId { get; set; }
        public Nullable<long> EditorId { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<bool> IsInStore { get; set; }
        public Nullable<bool> IsInExpendture { get; set; }
        public Nullable<bool> IsInJournal { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    }
}
