//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsTest
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string UndividedCode { get; set; }
        public string NameA { get; set; }
        public string NameE { get; set; }
        public int SectionId { get; set; }
        public int UnitId { get; set; }
        public int SupplierID { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public double CostPrice { get; set; }
        public double SalePrice { get; set; }
        public Nullable<double> LeastSalePrice { get; set; }
        public Nullable<double> SalePriceInWholesale { get; set; }
        public Nullable<double> LeastSalePriceInWholesale { get; set; }
        public Nullable<int> RequestingBoundary { get; set; }
        public string Description { get; set; }
        public string ManufactoryCode { get; set; }
        public double Beginning { get; set; }
        public double Warehouse1 { get; set; }
        public Nullable<double> OnHand { get; set; }
        public Nullable<int> Old_ID { get; set; }
        public Nullable<int> Old_ParentID { get; set; }
        public Nullable<int> Old_UnitID { get; set; }
        public Nullable<int> Old_SectionID { get; set; }
        public Nullable<int> Old_SupplierID { get; set; }
        public Nullable<bool> HasOneInternalUnit { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> NumOfInternalItems { get; set; }
        public byte[] UpdateStamp { get; set; }
        public string SupplierCode { get; set; }
        public Nullable<int> UserID { get; set; }
        public int Free_Qty { get; set; }
        public string FreeItemCode { get; set; }
        public bool Expirable { get; set; }
        public Nullable<int> NotifyBefore { get; set; }
        public Nullable<int> AboveParentID { get; set; }
    }
}
