//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemControl
    {
        public ItemControl()
        {
            this.DTLBalanceForFirstPeriods = new HashSet<DTLBalanceForFirstPeriod>();
            this.DTLBalanceForLastPeriods = new HashSet<DTLBalanceForLastPeriod>();
            this.DTLMaterialsRequests = new HashSet<DTLMaterialsRequest>();
            this.DTLPeriodicalInventories = new HashSet<DTLPeriodicalInventory>();
            this.DTLPurchaseBills = new HashSet<DTLPurchaseBill>();
            this.DTLPurchaseChecks = new HashSet<DTLPurchaseCheck>();
            this.DTLPurchaseCheckTests = new HashSet<DTLPurchaseCheckTest>();
            this.DTLPurchaseReturns = new HashSet<DTLPurchaseReturn>();
            this.DTLReceiptOfMaterialsRequests = new HashSet<DTLReceiptOfMaterialsRequest>();
            this.DTLStoreReturns = new HashSet<DTLStoreReturn>();
            this.DTLTransferMaterials = new HashSet<DTLTransferMaterial>();
            this.DTLTransferRequests = new HashSet<DTLTransferRequest>();
            this.DTLTransferRequestTests = new HashSet<DTLTransferRequestTest>();
            this.InventoryDatas = new HashSet<InventoryData>();
            this.InventoryDataLogs = new HashSet<InventoryDataLog>();
            this.ItemPriceLogs = new HashSet<ItemPriceLog>();
            this.ItemSources = new HashSet<ItemSource>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CatID { get; set; }
        public Nullable<long> CatIDFK { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<long> ItemIDFk { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> CompanyID_Sup { get; set; }
        public Nullable<long> id_itemName { get; set; }
        public string ItemName { get; set; }
        public string itemFullName { get; set; }
        public Nullable<System.DateTime> DateWork { get; set; }
        public Nullable<System.DateTime> DateStop { get; set; }
        public Nullable<bool> IsStillWork { get; set; }
        public Nullable<bool> IsSingle { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<bool> IsWarntley { get; set; }
        public Nullable<int> YearW { get; set; }
        public Nullable<int> MonthW { get; set; }
        public Nullable<int> DayW { get; set; }
        public string LimitOrderUnit { get; set; }
        public Nullable<int> CountLimitOrder { get; set; }
        public byte[] ImagItem { get; set; }
        public byte[] ImageTradMark { get; set; }
        public string Origin { get; set; }
        public string Exporter { get; set; }
        public string BarCodeProduct { get; set; }
        public Nullable<bool> chkSecur1 { get; set; }
        public Nullable<bool> chkSecur2 { get; set; }
        public Nullable<bool> chkSecur3 { get; set; }
        public Nullable<bool> chkSecur4 { get; set; }
        public Nullable<bool> chkSecur5 { get; set; }
        public Nullable<bool> chkSecur6 { get; set; }
        public Nullable<bool> chkSecur7 { get; set; }
        public string MaxDurabilityAmunt { get; set; }
        public Nullable<int> MaxDurabilityUnit { get; set; }
        public string StoreNotic { get; set; }
        public Nullable<long> InventoryProcess { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<long> UnitModelID { get; set; }
        public Nullable<long> InventoryID { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public Nullable<double> DefultPrice { get; set; }
        public Nullable<double> CostPrice { get; set; }
        public string UserID { get; set; }
        public Nullable<long> uniteMountName { get; set; }
        public Nullable<long> ModelUnitID { get; set; }
        public Nullable<long> Insertticks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> OrderLimit { get; set; }
        public Nullable<decimal> MaxQuantity { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public string SupplierCode { get; set; }
        public Nullable<bool> UseSupplierCodeForSales { get; set; }
        public string FreeItemID { get; set; }
        public Nullable<int> FreeItemCount { get; set; }
        public Nullable<int> FreeOfferID { get; set; }
        public string Name { get; set; }
        public string Barcode { get; set; }
        public string Path { get; set; }
        public Nullable<long> CurrentAmount { get; set; }
        public string IDCode { get; set; }
        public string SupplierItemCode { get; set; }
        public bool IsItemRequiredInOrder { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<DTLBalanceForFirstPeriod> DTLBalanceForFirstPeriods { get; set; }
        public virtual ICollection<DTLBalanceForLastPeriod> DTLBalanceForLastPeriods { get; set; }
        public virtual ICollection<DTLMaterialsRequest> DTLMaterialsRequests { get; set; }
        public virtual ICollection<DTLPeriodicalInventory> DTLPeriodicalInventories { get; set; }
        public virtual ICollection<DTLPurchaseBill> DTLPurchaseBills { get; set; }
        public virtual ICollection<DTLPurchaseCheck> DTLPurchaseChecks { get; set; }
        public virtual ICollection<DTLPurchaseCheckTest> DTLPurchaseCheckTests { get; set; }
        public virtual ICollection<DTLPurchaseReturn> DTLPurchaseReturns { get; set; }
        public virtual ICollection<DTLReceiptOfMaterialsRequest> DTLReceiptOfMaterialsRequests { get; set; }
        public virtual ICollection<DTLStoreReturn> DTLStoreReturns { get; set; }
        public virtual ICollection<DTLTransferMaterial> DTLTransferMaterials { get; set; }
        public virtual ICollection<DTLTransferRequest> DTLTransferRequests { get; set; }
        public virtual ICollection<DTLTransferRequestTest> DTLTransferRequestTests { get; set; }
        public virtual ICollection<InventoryData> InventoryDatas { get; set; }
        public virtual ICollection<InventoryDataLog> InventoryDataLogs { get; set; }
        public virtual Item Item { get; set; }
        public virtual ModelUnit ModelUnit { get; set; }
        public virtual StoresCompany StoresCompany { get; set; }
        public virtual ICollection<ItemPriceLog> ItemPriceLogs { get; set; }
        public virtual ICollection<ItemSource> ItemSources { get; set; }
    }
}
