//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAmount
    {
        public ItemAmount()
        {
            this.DTLBalanceForFirstPeriods = new HashSet<DTLBalanceForFirstPeriod>();
            this.DTLBalanceForLastPeriods = new HashSet<DTLBalanceForLastPeriod>();
            this.DTLMaterialsRequests = new HashSet<DTLMaterialsRequest>();
            this.DTLPurchaseChecks = new HashSet<DTLPurchaseCheck>();
            this.DTLReceiptOfMaterialsRequests = new HashSet<DTLReceiptOfMaterialsRequest>();
            this.DTLStoreReturns = new HashSet<DTLStoreReturn>();
            this.DTLTransferMaterials = new HashSet<DTLTransferMaterial>();
            this.DTLTransferRequests = new HashSet<DTLTransferRequest>();
            this.InventoryDatas = new HashSet<InventoryData>();
        }
    
        public long id { get; set; }
        public long IdItemContro { get; set; }
        public string ItemAmountCode { get; set; }
        public Nullable<long> AmountName { get; set; }
        public Nullable<float> CountUnit { get; set; }
        public Nullable<decimal> DefultPrice { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<bool> Defult { get; set; }
        public Nullable<int> Periorty { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
    
        public virtual ICollection<DTLBalanceForFirstPeriod> DTLBalanceForFirstPeriods { get; set; }
        public virtual ICollection<DTLBalanceForLastPeriod> DTLBalanceForLastPeriods { get; set; }
        public virtual ICollection<DTLMaterialsRequest> DTLMaterialsRequests { get; set; }
        public virtual ICollection<DTLPurchaseCheck> DTLPurchaseChecks { get; set; }
        public virtual ICollection<DTLReceiptOfMaterialsRequest> DTLReceiptOfMaterialsRequests { get; set; }
        public virtual ICollection<DTLStoreReturn> DTLStoreReturns { get; set; }
        public virtual ICollection<DTLTransferMaterial> DTLTransferMaterials { get; set; }
        public virtual ICollection<DTLTransferRequest> DTLTransferRequests { get; set; }
        public virtual ICollection<InventoryData> InventoryDatas { get; set; }
        public virtual ModelUnit ModelUnit { get; set; }
    }
}
