//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPriceLog
    {
        public long ID { get; set; }
        public long ItemAmountID { get; set; }
        public double PurchasePrice { get; set; }
        public double DefultPrice { get; set; }
        public double CostPrice { get; set; }
        public Nullable<long> LUU { get; set; }
        public System.DateTime ChangeDate { get; set; }
    
        public virtual ItemControl ItemControl { get; set; }
    }
}
