//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeavingRule
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> MaxAlowedPeriod { get; set; }
        public Nullable<int> MaxPeriodType { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> AllDeptsAllowed { get; set; }
        public Nullable<bool> AllJobTitleAllowed { get; set; }
        public Nullable<bool> AllEmployeementStatusAllowed { get; set; }
        public Nullable<int> MinServicePeriodAllowed { get; set; }
        public Nullable<int> MinServicePeriodAllowedType { get; set; }
        public Nullable<int> MaxServicePeriodAllowed { get; set; }
        public Nullable<int> MaxServicePeriodAllowedType { get; set; }
        public Nullable<bool> IsPermetionORVacation { get; set; }
        public Nullable<byte> Frequencey { get; set; }
    }
}
