//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerData
    {
        public long id { get; set; }
        public string LedgerName { get; set; }
        public string Descrip { get; set; }
        public Nullable<decimal> Depit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string InDate { get; set; }
        public string Notic { get; set; }
    }
}
