//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasureCard
    {
        public MeasureCard()
        {
            this.ReceiveStages = new HashSet<ReceiveStage>();
        }
    
        public long MeasureCardID { get; set; }
        public Nullable<System.DateTime> MeasureCardDate { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<long> AssayID { get; set; }
        public Nullable<double> Num { get; set; }
        public Nullable<long> EmpID { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public string Notes { get; set; }
    
        public virtual Assay Assay { get; set; }
        public virtual ICollection<ReceiveStage> ReceiveStages { get; set; }
    }
}
