//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mob_type
    {
        public Nullable<short> n { get; set; }
        public string c_no { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string mob_model { get; set; }
        public Nullable<float> mob_price { get; set; }
        public bool cash { get; set; }
        public Nullable<float> to { get; set; }
        public Nullable<float> money { get; set; }
        public Nullable<float> dis { get; set; }
        public Nullable<float> add { get; set; }
        public Nullable<float> @for { get; set; }
        public string name { get; set; }
        public Nullable<float> total_price { get; set; }
        public Nullable<float> elraseed { get; set; }
        public Nullable<System.DateTime> p_date { get; set; }
        public Nullable<float> month_ins { get; set; }
        public Nullable<int> no { get; set; }
        public string notes { get; set; }
        public Nullable<int> invoice_no { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public int mobno { get; set; }
    }
}
