//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelUnit
    {
        public ModelUnit()
        {
            this.DTLMaterialsRequests = new HashSet<DTLMaterialsRequest>();
            this.DTLPurchaseBills = new HashSet<DTLPurchaseBill>();
            this.DTLPurchaseChecks = new HashSet<DTLPurchaseCheck>();
            this.DTLPurchaseReturns = new HashSet<DTLPurchaseReturn>();
            this.DTLReceiptOfMaterialsRequests = new HashSet<DTLReceiptOfMaterialsRequest>();
            this.DTLStoreReturns = new HashSet<DTLStoreReturn>();
            this.DTLTransferMaterials = new HashSet<DTLTransferMaterial>();
            this.DTLTransferMaterialsNews = new HashSet<DTLTransferMaterialsNew>();
            this.DTLTransferRequests = new HashSet<DTLTransferRequest>();
            this.InventoryDataLogs = new HashSet<InventoryDataLog>();
            this.ItemAmounts = new HashSet<ItemAmount>();
            this.ItemControls = new HashSet<ItemControl>();
        }
    
        public long ModelUnitID { get; set; }
        public long UnitModelID { get; set; }
        public string UnitName { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<bool> isDefault { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<long> LUU { get; set; }
        public long ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<DTLMaterialsRequest> DTLMaterialsRequests { get; set; }
        public virtual ICollection<DTLPurchaseBill> DTLPurchaseBills { get; set; }
        public virtual ICollection<DTLPurchaseCheck> DTLPurchaseChecks { get; set; }
        public virtual ICollection<DTLPurchaseReturn> DTLPurchaseReturns { get; set; }
        public virtual ICollection<DTLReceiptOfMaterialsRequest> DTLReceiptOfMaterialsRequests { get; set; }
        public virtual ICollection<DTLStoreReturn> DTLStoreReturns { get; set; }
        public virtual ICollection<DTLTransferMaterial> DTLTransferMaterials { get; set; }
        public virtual ICollection<DTLTransferMaterialsNew> DTLTransferMaterialsNews { get; set; }
        public virtual ICollection<DTLTransferRequest> DTLTransferRequests { get; set; }
        public virtual ICollection<InventoryDataLog> InventoryDataLogs { get; set; }
        public virtual ICollection<ItemAmount> ItemAmounts { get; set; }
        public virtual ICollection<ItemControl> ItemControls { get; set; }
        public virtual UnitModel UnitModel { get; set; }
    }
}
