//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MosiratElrwatebLOG
    {
        public long Id { get; set; }
        public Nullable<long> MosiratElrwtebDTLId { get; set; }
        public Nullable<long> MosiratElrwtebHDId { get; set; }
        public Nullable<long> EmpIdCode { get; set; }
        public Nullable<decimal> OverTime { get; set; }
        public Nullable<long> HRJobID { get; set; }
        public Nullable<long> SalaryItemID { get; set; }
        public Nullable<decimal> ItemValue { get; set; }
        public string SalaryItemName { get; set; }
        public Nullable<bool> TypeADD { get; set; }
        public Nullable<bool> Ispublic { get; set; }
        public Nullable<long> HRDepartmentID { get; set; }
        public Nullable<bool> IsRate { get; set; }
        public Nullable<long> RateFrom { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    }
}
