//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MosiratElrwtebHD
    {
        public long Id { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> year { get; set; }
    }
}
