//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivationAndDeduction
    {
        public long Id { get; set; }
        public Nullable<long> EmployeIdCode { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<bool> type { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string Note { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<long> MotivationAndDeductionsByDaysID { get; set; }
    }
}
