//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Op_ReportData
    {
        public byte[] WaterMark { get; set; }
        public int Transparency { get; set; }
        public bool UseLogo { get; set; }
        public string Row1 { get; set; }
        public string Row2 { get; set; }
        public string Row3 { get; set; }
        public string ERow1 { get; set; }
        public string ERow2 { get; set; }
        public string ERow3 { get; set; }
        public string Footer1 { get; set; }
        public string Footer2 { get; set; }
        public string EFooter1 { get; set; }
        public string EFooter2 { get; set; }
    }
}
