//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnershipData
    {
        public long id { get; set; }
        public string OwnershipName { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Curantvalue { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
    }
}
