//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Permission
    {
        public Payment_Permission()
        {
            this.Payment_Data = new HashSet<Payment_Data>();
        }
    
        public long Idcode { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> PermissionDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public string Paymentname { get; set; }
        public Nullable<long> EmpID { get; set; }
        public Nullable<long> ContractID { get; set; }
        public Nullable<long> PeriodID { get; set; }
        public Nullable<long> installmentid { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public string Notes { get; set; }
        public Nullable<long> CustID { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Installment Installment { get; set; }
        public virtual ICollection<Payment_Data> Payment_Data { get; set; }
    }
}
