//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SafeHistoryPlaning
    {
        public long Id { get; set; }
        public Nullable<long> IdSafeHistory { get; set; }
        public string VoucherNum { get; set; }
        public Nullable<decimal> VoucherValue { get; set; }
        public string VoucherType { get; set; }
        public string PayeName { get; set; }
        public Nullable<System.DateTime> DatePayability { get; set; }
        public string StatePay { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    }
}
