//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryItem
    {
        public SalaryItem()
        {
            this.EmployeeSalaryItems = new HashSet<EmployeeSalaryItem>();
        }
    
        public long SalaryItemID { get; set; }
        public string SalaryItemName { get; set; }
        public Nullable<decimal> SalaryItemDefaultValue { get; set; }
        public Nullable<bool> TypeADD { get; set; }
        public Nullable<int> PayingPeriod { get; set; }
        public Nullable<bool> Ispublic { get; set; }
        public Nullable<long> HRDepartmentID { get; set; }
        public Nullable<bool> IsRate { get; set; }
        public Nullable<long> RateFrom { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public long ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<EmployeeSalaryItem> EmployeeSalaryItems { get; set; }
    }
}
