//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesMainPublic
    {
        public long Idcode { get; set; }
        public Nullable<long> EmplId { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public string CustName { get; set; }
        public string PayWay { get; set; }
        public Nullable<decimal> BillCost { get; set; }
        public Nullable<decimal> TaxValue { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<bool> IsInStore { get; set; }
        public Nullable<bool> IsInJournal { get; set; }
        public Nullable<bool> IsInSafe { get; set; }
        public Nullable<bool> IsInBank { get; set; }
        public Nullable<long> SalesID { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<long> PeriodId { get; set; }
    }
}
