//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingApplicationActiveCode
    {
        public long Id { get; set; }
        public string ActiveCode { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<bool> Allow { get; set; }
        public string Owner { get; set; }
        public Nullable<long> CountLogin { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    }
}
