//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingApllicationInterface
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public string UserName { get; set; }
        public string SchemaName { get; set; }
        public string CaptionFormColor1 { get; set; }
        public string CaptionFormColor2 { get; set; }
        public string SkinName { get; set; }
        public Nullable<bool> IsDefult { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    }
}
