//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoresCompany
    {
        public StoresCompany()
        {
            this.HDBalanceForFirstPeriods = new HashSet<HDBalanceForFirstPeriod>();
            this.HDBalanceForLastPeriods = new HashSet<HDBalanceForLastPeriod>();
            this.HDMaterialsrequests = new HashSet<HDMaterialsrequest>();
            this.HDPeriodicalInventories = new HashSet<HDPeriodicalInventory>();
            this.HDReceiptOfMaterialsRequests = new HashSet<HDReceiptOfMaterialsRequest>();
            this.HDStoreReturns = new HashSet<HDStoreReturn>();
            this.HDTransferMaterials = new HashSet<HDTransferMaterial>();
            this.HDTransferRequests = new HashSet<HDTransferRequest>();
            this.InventoryDataLogs = new HashSet<InventoryDataLog>();
            this.ItemControls = new HashSet<ItemControl>();
        }
    
        public long StoreId { get; set; }
        public string StoreBuilding { get; set; }
        public string StoreName { get; set; }
        public string EmplId { get; set; }
        public byte[] Map { get; set; }
        public Nullable<long> BranchID { get; set; }
        public long AccountID { get; set; }
        public Nullable<bool> IsDefult { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public long ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<HDBalanceForFirstPeriod> HDBalanceForFirstPeriods { get; set; }
        public virtual ICollection<HDBalanceForLastPeriod> HDBalanceForLastPeriods { get; set; }
        public virtual ICollection<HDMaterialsrequest> HDMaterialsrequests { get; set; }
        public virtual ICollection<HDPeriodicalInventory> HDPeriodicalInventories { get; set; }
        public virtual ICollection<HDReceiptOfMaterialsRequest> HDReceiptOfMaterialsRequests { get; set; }
        public virtual ICollection<HDStoreReturn> HDStoreReturns { get; set; }
        public virtual ICollection<HDTransferMaterial> HDTransferMaterials { get; set; }
        public virtual ICollection<HDTransferRequest> HDTransferRequests { get; set; }
        public virtual ICollection<InventoryDataLog> InventoryDataLogs { get; set; }
        public virtual ICollection<ItemControl> ItemControls { get; set; }
    }
}
