//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierHistPlaningPay
    {
        public long Id { get; set; }
        public Nullable<long> IdSupplierHistory { get; set; }
        public string VoucherNum { get; set; }
        public string StatePay { get; set; }
        public string VoucherPaperType { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<float> CostActual { get; set; }
        public Nullable<float> CostFuture { get; set; }
        public Nullable<System.DateTime> DatePayability { get; set; }
        public Nullable<System.DateTime> DateEdit { get; set; }
        public Nullable<bool> IsDiscountAccelration { get; set; }
        public Nullable<decimal> DiscountRate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> Todate { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<int> Months { get; set; }
        public Nullable<int> Years { get; set; }
        public Nullable<bool> IsDiscountAchieved { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    }
}
