//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempEmployeesInfo
    {
        public long id { get; set; }
        public string Name { get; set; }
        public string stayNum { get; set; }
        public string stayFinishDate { get; set; }
        public string passportFinishDate { get; set; }
        public string passportNum { get; set; }
        public string job { get; set; }
        public string nationality { get; set; }
    }
}
