//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long ID { get; set; }
        public long EmpID { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.DateTime CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
        public Nullable<System.DateTime> LastInserted { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public short AccessMode { get; set; }
        public Nullable<short> CheckOutMode { get; set; }
        public string CheckInType { get; set; }
        public string CheckOutType { get; set; }
    }
}
