//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeMenuApplication
    {
        public long Id { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string DisplayValue { get; set; }
        public string DisplayValue_En { get; set; }
        public string FormName { get; set; }
        public Nullable<bool> WithParameters { get; set; }
        public Nullable<bool> AllowOpen { get; set; }
        public Nullable<int> UserSort { get; set; }
        public Nullable<int> ImageIndex { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<bool> Seperated { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public string Name { get; set; }
    }
}
