//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitModel
    {
        public UnitModel()
        {
            this.ModelUnits = new HashSet<ModelUnit>();
        }
    
        public long UnitModelID { get; set; }
        public string UnitModelName { get; set; }
        public Nullable<long> BasicUnitID { get; set; }
        public Nullable<long> InventoryUnitID { get; set; }
        public Nullable<long> SalesUnitID { get; set; }
        public Nullable<long> PurchaseUnitID { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<long> LUU { get; set; }
        public long ID { get; set; }
        public string Name { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual ICollection<ModelUnit> ModelUnits { get; set; }
    }
}
