//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public long Id { get; set; }
        public Nullable<long> IdCode { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> MaxCountUser { get; set; }
        public string State { get; set; }
        public string Descrip { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    }
}
