//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogInTransaction
    {
        public long Id { get; set; }
        public Nullable<long> EmplIdCode { get; set; }
        public System.DateTime LogInDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string LogType { get; set; }
        public string ReasonClose { get; set; }
        public string LUU { get; set; }
        public System.DateTime LUD { get; set; }
    }
}
