//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserName
    {
        public long Id { get; set; }
        public Nullable<long> EmplIdCode { get; set; }
        public Nullable<long> GroupId { get; set; }
        public string UserName1 { get; set; }
        public string PassWord { get; set; }
        public string UserType { get; set; }
        public Nullable<bool> ChangePassword { get; set; }
        public Nullable<bool> IsAllowLoginApplication { get; set; }
        public Nullable<int> CountDay { get; set; }
        public Nullable<System.DateTime> StopAcount { get; set; }
        public Nullable<System.DateTime> ReOpenIndate { get; set; }
        public string QuestRemembar { get; set; }
        public string AllowanceSerial { get; set; }
        public Nullable<bool> IsCoreAllowanceSerial { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<int> Role { get; set; }
        public string Name { get; set; }
    
        public virtual EmployedInfo EmployedInfo { get; set; }
    }
}
