//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AllBankHistory
    {
        public long Idcode { get; set; }
        public string Name { get; set; }
        public string AcountType { get; set; }
        public string AcountCrunceyType { get; set; }
        public string AcountNum { get; set; }
        public string AcountOwner { get; set; }
        public Nullable<decimal> FirstAccount { get; set; }
        public string Branch { get; set; }
        public string BranchAdress { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string Declaration { get; set; }
        public string Descrip { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<long> EmplId { get; set; }
        public string Type { get; set; }
        public string LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public long Id { get; set; }
        public Nullable<long> PeriodId { get; set; }
    }
}
