//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AllempData
    {
        public long IdCode { get; set; }
        public string Name { get; set; }
        public string Relgion { get; set; }
        public string Gender { get; set; }
        public string nationnality { get; set; }
        public string CountryName { get; set; }
        public string HRJobName { get; set; }
        public byte[] EmplImage { get; set; }
        public string NationalNum { get; set; }
    }
}
