//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_contractHdData
    {
        public long ContractID { get; set; }
        public string HRDepartmentName { get; set; }
        public Nullable<System.DateTime> contractDate { get; set; }
        public string Name { get; set; }
        public string empId { get; set; }
        public Nullable<double> TotalCost { get; set; }
    }
}
