//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Contracts_Payment_Details
    {
        public string Paymentname { get; set; }
        public Nullable<long> PaymentDataID { get; set; }
        public string PaymentType { get; set; }
        public string Notes { get; set; }
        public long InstallmentID { get; set; }
        public Nullable<long> ContractID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<decimal> InstallmentValue { get; set; }
        public Nullable<System.DateTime> InstallmentDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
    }
}
