//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CostCenters
    {
        public long ID { get; set; }
        public Nullable<long> IdParant { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> ExpectedCost { get; set; }
        public string Notice { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Protection { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    }
}
