//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_FullContractData
    {
        public long ContractID { get; set; }
        public Nullable<System.DateTime> contractDate { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string Name { get; set; }
        public Nullable<long> HRDDepartmentID { get; set; }
        public string HRDepartmentName { get; set; }
        public string PhoneNum { get; set; }
        public string Address { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<long> ContractIdItemDesc { get; set; }
        public string ContractItemDescription { get; set; }
        public long AssayID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<long> ProductUnitID { get; set; }
        public string UnitName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public long MeasureCardID { get; set; }
        public Nullable<System.DateTime> MeasureCardDate { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<long> Expr1 { get; set; }
        public Nullable<double> Num { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public long Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string WorkRatio { get; set; }
        public Nullable<long> Expr2 { get; set; }
        public long InstallmentID { get; set; }
        public Nullable<decimal> InstallmentValue { get; set; }
        public Nullable<System.DateTime> InstallmentDate { get; set; }
    }
}
