//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GeturentStock
    {
        public Nullable<long> StoreId { get; set; }
        public Nullable<long> ItemCode { get; set; }
        public string ItemName { get; set; }
        public string Amount { get; set; }
        public Nullable<double> StockOnHand { get; set; }
        public Nullable<decimal> PriceUnit { get; set; }
        public string Catogry { get; set; }
    }
}
