//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_InventoryDataStock
    {
        public Nullable<long> ItemCode { get; set; }
        public string ItemName { get; set; }
        public double CurentStock { get; set; }
        public string UnitName { get; set; }
        public Nullable<long> StoreId { get; set; }
        public Nullable<long> Amount { get; set; }
    }
}
