//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ItemsFullData
    {
        public string Category { get; set; }
        public string Item { get; set; }
        public string Mark { get; set; }
        public string Model { get; set; }
        public long CategoryId { get; set; }
        public long ItemId { get; set; }
        public long MarkId { get; set; }
        public long ModelId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
    }
}
