//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ItemsSearch
    {
        public long ItemControlID { get; set; }
        public Nullable<long> CatID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string ItemName { get; set; }
        public string ModelName { get; set; }
        public Nullable<System.DateTime> DateWork { get; set; }
        public Nullable<System.DateTime> DateStop { get; set; }
        public Nullable<bool> IsStillWork { get; set; }
        public Nullable<bool> IsSingle { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<bool> IsWarntley { get; set; }
        public Nullable<int> YearW { get; set; }
        public Nullable<int> MonthW { get; set; }
        public Nullable<int> DayW { get; set; }
        public string LimitOrderUnit { get; set; }
        public Nullable<int> CountLimitOrder { get; set; }
        public byte[] ImagItem { get; set; }
        public byte[] ImageTradMark { get; set; }
        public string Origin { get; set; }
        public string Exporter { get; set; }
        public string BarCodeProduct { get; set; }
        public Nullable<bool> chkSecur1 { get; set; }
        public Nullable<bool> chkSecur2 { get; set; }
        public Nullable<bool> chkSecur3 { get; set; }
        public Nullable<bool> chkSecur4 { get; set; }
        public Nullable<bool> chkSecur5 { get; set; }
        public Nullable<bool> chkSecur7 { get; set; }
        public Nullable<bool> chkSecur6 { get; set; }
        public string MaxDurabilityAmunt { get; set; }
        public Nullable<int> MaxDurabilityUnit { get; set; }
        public string StoreNotic { get; set; }
        public Nullable<long> InventoryProcess { get; set; }
        public Nullable<long> UnitModelID { get; set; }
        public Nullable<long> InventoryID { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public string UserID { get; set; }
        public Nullable<long> ModelUnitID { get; set; }
        public Nullable<long> Insertticks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> OrderLimit { get; set; }
        public Nullable<decimal> MaxQuantity { get; set; }
        public string BaseUnit { get; set; }
        public long ItemAmountID { get; set; }
        public string ChildUnit { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public string ItemCode { get; set; }
        public string FullName { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
    }
}
