//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MosiratElrwateb
    {
        public long IdCode { get; set; }
        public string Name { get; set; }
        public Nullable<long> Nationalty { get; set; }
        public string HRJobName { get; set; }
        public Nullable<long> SalaryItemID { get; set; }
        public Nullable<decimal> ItemValue { get; set; }
        public string SalaryItemName { get; set; }
        public Nullable<bool> TypeADD { get; set; }
        public Nullable<bool> Ispublic { get; set; }
        public Nullable<bool> IsRate { get; set; }
        public Nullable<long> RateFrom { get; set; }
        public Nullable<long> HRJobID { get; set; }
        public Nullable<long> HRDepartmentID { get; set; }
    }
}
