//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_RequestData
    {
        public long Id { get; set; }
        public string DateMaterialsrequest { get; set; }
        public Nullable<long> ContractID { get; set; }
        public string StoreEmpID { get; set; }
        public string ReqEmpId { get; set; }
        public Nullable<long> StoreID { get; set; }
        public Nullable<long> RequestEmpID { get; set; }
        public Nullable<long> EmpID { get; set; }
        public Nullable<byte> state { get; set; }
    }
}
