//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SalesAllDataPublic
    {
        public long Idcode { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public string CustName { get; set; }
        public string PayWay { get; set; }
        public Nullable<decimal> BillCost { get; set; }
        public Nullable<decimal> TaxValue { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string Amount { get; set; }
        public Nullable<int> UnitsInAmount { get; set; }
        public Nullable<float> CountAmount { get; set; }
        public Nullable<decimal> PriceUnit { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<float> Total { get; set; }
        public string LUU { get; set; }
        public Nullable<long> PeriodId { get; set; }
    }
}
