//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_StoreReturns
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> DateHDStoreReturns { get; set; }
        public string StoreEmpID { get; set; }
        public string EmpTec { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<long> StoreID { get; set; }
    }
}
