//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SummaryCash
    {
        public long Idcode { get; set; }
        public string SafeBoxName { get; set; }
        public Nullable<double> GrossDebit { get; set; }
        public Nullable<double> GrossCredit { get; set; }
        public Nullable<double> Balance { get; set; }
    }
}
