//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SupplierNetAccount
    {
        public long IdCode { get; set; }
        public string Name { get; set; }
        public string CompanyName { get; set; }
        public Nullable<decimal> SumCredit { get; set; }
        public Nullable<decimal> SumDebit { get; set; }
        public Nullable<decimal> NetAccount { get; set; }
    }
}
