//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SummarySalesReturn
    {
        public long Idcode { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<long> IdcodeSalesMain { get; set; }
        public Nullable<decimal> Checkpay { get; set; }
        public Nullable<decimal> CashPay { get; set; }
        public Nullable<decimal> delayedPay { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> DateBill { get; set; }
        public Nullable<long> PeriodId { get; set; }
    }
}
