//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SummaryBank
    {
        public long Idcode { get; set; }
        public string Name { get; set; }
        public string Branch { get; set; }
        public string AcountNum { get; set; }
        public string AcountCrunceyType { get; set; }
        public decimal GrossDebit { get; set; }
        public decimal GrossCredit { get; set; }
        public decimal Balance { get; set; }
    }
}
