//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacation
    {
        public long Id { get; set; }
        public Nullable<bool> Type { get; set; }
        public Nullable<long> EmployeIdCode { get; set; }
        public Nullable<long> ParentID { get; set; }
        public Nullable<System.DateTime> fromDate { get; set; }
        public Nullable<int> VacCount { get; set; }
        public Nullable<System.DateTime> toDate { get; set; }
        public string Note { get; set; }
        public Nullable<long> vacationTypeId { get; set; }
        public Nullable<long> LUU { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
    }
}
