//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_HRDE
    {
        public long IdCode { get; set; }
        public string Name { get; set; }
        public Nullable<long> IdParant { get; set; }
        public string HRJobName { get; set; }
        public string HRDepartmentName { get; set; }
        public Nullable<long> DEIdParant { get; set; }
        public string JopPath { get; set; }
        public Nullable<long> HRDepartmentID { get; set; }
        public string DepartmenPath { get; set; }
        public Nullable<long> HRJobID { get; set; }
        public string jopTree { get; set; }
        public string DepartmentTRee { get; set; }
    }
}
